os: linux
dist: trusty
group: stable
language: python
script:
  - mkdir templates
  - cd $TRAVIS_BUILD_DIR/whitebox_studio
  - npm install
  - npm run build
  - cp build/index.html ../templates
  - cp -r build/static ../
deploy:
  provider: heroku
  api_key:
    secure: "ae08d8bd-7fd8-4f63-8cbb-a95d98e0282d"
  app: whitebox-rfft
  run: "echo Deployed from Travis"
  strategy: git