os: linux
dist: trusty
group: stable
language: python
cache:
  directories:
    - node_modules
  - pip
script:
  - cd whitebox_studio
  - npm install
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: "ae08d8bd-7fd8-4f63-8cbb-a95d98e0282d"
  app: whitebox-rfft
  run: "echo Deployed from Travis"
  strategy: git
