os: linux
dist: trusty
group: stable
language: python
cache:
  directories:
    - $HOME/virtualenv
    - $TRAVIS_BUILD_DIR/whitebox_studio/node_modules
install:
  - echo Mock installation
script:
  - mkdir -p templates
  - cd $TRAVIS_BUILD_DIR/whitebox_studio
  - npm install
  - npm run build
  - cp build/index.html ../templates
  - cp -rf build/static ../
  - rm -rf build
  - cd ..
  - git add templates/
  - git add static/
  - git commit -am 'Added React build files'
  - ls
deploy:
  provider: heroku
  api_key:
    secure: "ae08d8bd-7fd8-4f63-8cbb-a95d98e0282d"
  app: whitebox-rfft
  run: "echo Deployed from Travis"
  skip_cleanup: true
  strategy: git
